---
version: 3.9.1
hassio_api: true
slug: nginx_proxy_custom
name: NGINX Home Assistant SSL proxy
description: An SSL/TLS proxy
url: https://github.com/zenturacp/hass-custom-addons/tree/main/nginx_proxy
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - ssl
  - share
  - homeassistant_config
options:
  domain: null
  hsts: max-age=31536000; includeSubDomains
  certfile: /homeassistant_config/.cloud/remote_fullchain.pem
  keyfile: /homeassistant_config/.cloud/remote_private.pem
  cloudflare: false
  customize:
    active: false
    default: nginx_proxy_default*.conf
    servers: nginx_proxy/*.conf
ports:
  443/tcp: 443
  80/tcp: null
schema:
  domain: str
  hsts: str
  certfile: str
  keyfile: str
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
